### ISSUE TITLE
[Design Planning] Discussion

### ISSUE THREAD

**Issue by lvyuemeng** [lvyuemeng/pulith#1]
### Layout

1. cli
2. system
3. runtime
4. version
5. package
6. env

### Update
> ### CLI
> 
> Format `pulith [ops] [target]`
> 
> - add `i`
> - remove `rm`
> - register `reg`
> - upgrade `up`
> - uninstall
> - activate
> - list `l`
> - ...

### System

- system package manager semantics
- console control (set temporary local console)
- OS, arch semantics
- path control

## **Deprecated**

> ### Version
> 
> 1. version semantics.
> 2. version manager connection.
> 3. accept info from `package`.
> 4. version control ops:
>    - transfer installation strategy.
>      - if vm handled version manager.
>      - if self_vm handled self-versioned.
>      - if native no need.
>      - if prebuilt handled env info.

## **Deprecated**

> ### Package
> 1. Installation strategy semantics.
>    - self_vm
>    - vm (handled by preinstalled version manager)
>      - list version managers.
>    - native (extract env info from installation script)
>    - prebuilt
>      - fetch
>      - extract
>      - config
>      - env_set
> 3. package plugin (remove manual maintaining).
>    - example:
>      - rust
>        - Possible files for private operation
>        - index/src (interfaces, list below.)
>    - register
>      - register()
>    - env
>      - detect_version_files() -- local version requirement detection
>      - fetch_version() -- collect version info online.
>      - locate_exec()
>    - download
>      - fetch_prebuilt()
>    - installation/remove
>      - install_self_vm()
>      - install_vm() -- check and install vm first.
>      - install_native()
>      - install_prebuilt()

### env
1. accept info from `package`, `version` for ops.
2. env strategy in priority:
   - vm
     - including self version manager (for example: bun, rust)
   - shims
     - accept `locate_exec` from `package`:
       - `run version`
       - detect local proj
         - if version conflict, resolve to change
     - path
     - script
   - symlink (not recommend)
     - path
     - ops
   - activation (local proj if necessary)

### Runtime
**Path Storage**
- home (home path)
- cur (work path)
- **store**
  - root (the store path of infos that list below)
  - bin_dir
  - cache_dir
  - temp_dir
  - plugin_dir
  - tools_dir  (store remote versions and portable package)

Construct a test sandbox...(May need other Lua package aid)

**Config**
- config
  - config_global
  - config_local
  - config_all

**Comment by lvyuemeng** [comment]
Search backend and its tool by rayon and using cache designed for each backend.
Create Parse<T> for backend and Cache.
Create cache for List.
Each backend access snap and Cache.

**Comment by lvyuemeng** [comment]
### Template Setting
Read in toml in ~/.config/pulith/config.toml or ~/.config/pulith.toml

profiles with name(otherwise "default"):
```toml
[default]

# profile_name.backend.verb
# take the given string as flags.
[default.{backend}.install]
"--id" = "..."

# parse template to create alias
# {{ number }}: {{ 1 }} for first args etc..
# {{ flag }}: {{ package }} for --package etc..
# {{ }}: insert rest of multiple args
[default.alias]
"install_by_id" = "install @{{ 1 }}:{{ 2 }} --id {{ 3 }}"
```

**Comment by lvyuemeng** [comment]
### Template Setting

Read in toml in ~/.config/pulith/config.toml or ~/.config/pulith.toml

Profiles with name(otherwise "default"):

```toml
[default]

# support regex for name.
# support string or "y" as true for flags without args.

# define: "replace" = "original"
# profile_name.backend.verb.alias
[default.{backend}.install.alias]
"--path" = "--target-path"

# profile_name.backend.alias
[default.{backend}.alias]
"--slience" =  "--quiet"
"-s" =  "-q"

# profile_name.backend.verb.flag
[default.{backend}.install.flag]
"--verbose" = "y"

# profile_name.backend.flag
[default.{backend}.flag]
"--output" = "--log"

# parse template to create alias
# { num }: positional args. { 0 } for first args etc..
# { * }: multiple args. should be in the end.
# { --flag }: flags define, single args. { --package -p } for --package and -p
# { --flag * }: flags define, multiple args { --package -p } for --package and -p

[default.alias]
"install_by_id" = "install @{{ 0 }}:{{ 1 }} --id {{ 2 }}"

# evaluated in shell(important! install external thing!)
# defined in scipts/insall_by_winget.pwsh
# winget install $0
# defined in scripts/install_by_apt.sh
# sudo apt install $0
[default.alias.script]
"install_by_winget" = "scripts/install_by_winget.pwsh"
"install_by_apt" = "scripts/install_by_apt.sh"

[config]
editor = "nvim"
```

Template(tera):

```toml
# data
# in data/alice.toml
alice = "Alice"
# in config.toml
name = {{ alice }}

# regex
"^(-p|--path)" = "--target-path"

# inheritance
[default]
... defined for default

[profile1]
inheritance = "default"
```
